version: '3'
services:  
  mysql-container:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: Password123!
      MSSQL_DATABASE: MyDatabase
      ACCEPT_EULA: "Y"
    user: root
    ports:
      - "1433:1433"
    networks:
      - my-network
  nodejs-container:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - my-network

networks:
  my-network:
